version: '3'
services:
  app:
    image: ghcr.io/jastin-infj/battle-vision/react-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: ["yarn","start"]