version: "3"
services:
  web-react:
    image: web-react
    container_name: web-react
    build:
      context: ./webApp/
      dockerfile: Dockerfile
    volumes:
      - ./webApp:/usr/src/app/webApp
      - front_node_modules:/usr/src/app/webApp/node_modules
    ports:
      - "3000:3000"
    command: sh -c "cd webApp && yarn start"

  web:
    image: nginx:1.23.4-alpine3.17
    container_name: nginx
    build:
      context: ./web/
      dockerfile: Dockerfile
    volumes:
    - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./web/build:/usr/share/nginx/html
    ports:
    - "8080:80"

volumes:
  front_node_modules: