version: "3"
services:
  web:
    image: web
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - front_node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "yarn start"

volumes:
  front_node_modules: