version: '3'
services:
  app:
    image: us-central1-docker.pkg.dev/app-battle-vision/app-battle-vision-ar/react-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: ["yarn", "start"]