version: "3"
services:
  web:
    image: service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: ["yarn","start"]
    ports:
      - "3000:3000"