version: '3'
services:
  app:
    image: react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - ./build:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - 3000:3000