ARG NODE_VERSION=18.15.0
ARG ALPINE_VERSION=3.17
ARG NGINX_VERSION=1.23

FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS builder

# /app $HOME  ~ とする

WORKDIR /usr/src/app

# yarn install が出来ないため

# ~ 直下
COPY package*.json ./
COPY yarn.lock ./

RUN yarn install

# node_modules and ソースコード直下
COPY . .

# 公開用 index.html 作成 
RUN yarn build

FROM nginx:${NGINX_VERSION}-alpine${ALPINE_VERSION} AS server

COPY . /home/nginx

RUN cd /home/nginx; \
    mv docker-entrypoint.sh /usr/local/bin; \
    chmod +x /usr/local/bin/docker-entrypoint.sh;

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]