version: "3"
services:
  app:
    image: python
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./django_test:/usr/src/app/app
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    ports:
    - "8080:8000"