version: 2
jobs:
    test_frontend:
        docker:
          - image: circleci/node:18.15.0
    steps:
        - checkout
        - run: yarn install
        - run: yarn start
workflows:
    version: 2
    run_test:
        jobs:
            - test_frontend