name: docker-build-push ghcr.io
run-name: ${{ github.actor }} ${{ github.ref }}-${{ github.sha }}
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: ubuntu-22.04
    environment: develop
    steps:
    - 
      name: Github checkout OK
      uses: actions/checkout@v3
    
    - name: Get Docker push tag OK
      id: get_docker_image_tag
      run: |
        echo  "DOCKER_PUSH_URL=${{ vars.GIT_REGISTRY_URL }}/${{ vars.GIT_ACCOUNT_LOGIN_NAME }}/${{ vars.DOCKER_PUSH_REPOSITORY }}/${{ vars.DOCKER_PUSH_IMAGE }}:${{ vars.DOCKER_PUSH_TAG }}" >> $GITHUB_OUTPUT
    - 
      name: GitHub Container Registry Login OK
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REACT_APP }}

    - 
      name: yarn intall Using React OK
      run: |
        yarn install
    - 
      name: Ubuntu file ls OK
      run: |
        ls -a
    - 
      name: Ubuntu file owner OK
      run: |
        ls -al
    -
      name: docker version OK
      run: |
        docker --version
    
    -
      name: docker compose version OK
      run: |
        docker compose --version
    - 
      name: npm version OK
      run: |
        npm -v
    - 
      name: npx version OK
      run: |
        npx -v
    - 
      name: node version OK
      run: |
        node -v
    - 
      name: yarn version OK
      run: |
        yarn --version
    -
      name: docker compose build OK
      run: |
        docker compose -f ${{ vars.DOCKER_COMPOSE_YAL_FILE_GCR }} build
    
    -
      name: docker images ls OK
      run: |
        docker images
    -
      name: docker-compose up OK
      run: |
        docker compose -f ${{ vars.DOCKER_COMPOSE_YAL_FILE_GCR }}  up -d
    -
      name: docker container remove all OK
      run: |
        docker rm -f `docker ps -a -q`
    -
      name: docker push OK
      run: |
        docker push ${{ steps.get_docker_image_tag.outputs.DOCKER_PUSH_URL }}